server:
  port: 6070
spring:
  data:
    mongodb:
      host: 172.30.3.165
      port: 27017
      database: fund
      username: fundAppropriation
      password: fundAppropriation
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
oauth:
  hide-user-not-found: true